site_name: My Docs
site_url: https://juniorxyz.github.io/myCMS
theme:
  name: material
  palette:
    primary: black
  features:
    - content.code.copy
    - content.code.annotate

repo_url: https://github.com/junior-stack/myCMS

repo_name: junior-stack/myCMS

# Add the hook file
hooks:
  - hooks.py

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  # - pymdownx.highlight:
  #     linenums: true
  - codehilite
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascript/mathjax.js
  - javascript/collapseCodeblock.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - css/collapseCodeblock.css

plugins:
  - blog:
      blog_dir: .
